/**
 * 省级地址数据
 * 省级数据不会经常变动，可以写死在应用中，减少用户等待时常，减轻服务器压力
 */
export let province = [
        {
            "id":2400,
            "name":"安徽",
            "parentId":0,
            "parentName":""
        },
        {
            "id":5300,
            "name":"澳门",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1100,
            "name":"北京",
            "parentId":0,
            "parentName":""
        },
        {
            "id":9400,
            "name":"钓鱼岛",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2600,
            "name":"福建",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3800,
            "name":"甘肃",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2900,
            "name":"广东",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3000,
            "name":"广西",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3400,
            "name":"贵州",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3300,
            "name":"海南",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1500,
            "name":"河北",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1700,
            "name":"河南",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2000,
            "name":"黑龙江",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2700,
            "name":"湖北",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2800,
            "name":"湖南",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1900,
            "name":"吉林",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2200,
            "name":"江苏",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3100,
            "name":"江西",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1800,
            "name":"辽宁",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2100,
            "name":"内蒙古",
            "parentId":0,
            "parentName":""
        },
        {
            "id":4000,
            "name":"宁夏",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3900,
            "name":"青海",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2300,
            "name":"山东",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1600,
            "name":"山西",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3700,
            "name":"陕西",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1200,
            "name":"上海",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3200,
            "name":"四川",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1300,
            "name":"天津",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3600,
            "name":"西藏",
            "parentId":0,
            "parentName":""
        },
        {
            "id":5200,
            "name":"香港",
            "parentId":0,
            "parentName":""
        },
        {
            "id":4100,
            "name":"新疆",
            "parentId":0,
            "parentName":""
        },
        {
            "id":3500,
            "name":"云南",
            "parentId":0,
            "parentName":""
        },
        {
            "id":2500,
            "name":"浙江",
            "parentId":0,
            "parentName":""
        },
        {
            "id":1400,
            "name":"重庆",
            "parentId":0,
            "parentName":""
        }
    ];
